# MinePermit Default Configuration File
#
# This file is the default configuration file for 
# MinePermit.

WorldPermitAreas:                         #All world configs go under here.
  world:                                  #The name of the world
    allowMiningUnspecifiedBlocks: false   #Whether blocks not specified under 'prices' can be mined
    effectiveDepth: 65                 #Below what depth should permits be required?
    prices:                            #Prices for the permits in this permit area. Does not cascade to children.
      UNIVERSAL:                       #The material type. If the name is 'UNIVERSAL', then the price information is used for the UniversalPermit
        types:                         #The different types of permits to use
          COUNTED:                     #The type of permit
            price: 1000                #The price to buy the permit
            amount: 50                 #How much time/blocks the player gets to use/mine for the permit.
          TIMED:
            price: 10000
            amount: 3600
      GOLD_ORE:
        types:
          COUNTED:
            price: 100
            amount: 30
          TIMED:
            price: 300
            amount: 1000
      IRON_ORE:
        types:
          COUNTED:
            price: 50
            amount: 40
      LAPIS_ORE:                           #If its empty, it cannot be mined.
        types:                           #Just make sure to have the 'types' section
      COAL:
        types:
          COUNTED:
            price: 30
            amount: 70
      STONE:
        types:
          TIMED:
            price: 10
            amount: 60000
    children:                              #PermitAreas that are contained by this Permit Area
      DasMine:                             #The name (doesnt really do anything)
        x1: 123                            #Coordinates within the world. NOT respective to parent permit area
        z1: 2
        x2: 321
        z2: 56
        allowMiningUnspecifiedBlocks: true
        effectiveDepth: 70
        prices:
          STONE:
            types:
              COUNTED:
                price: 600
                amount: 60
