main: net.minecore.minepermit.MinePermit
author: Numenorean95
name: MinePermit
version: 1.0.0
softdepend: [Vault]

commands:
    permit:
        description: List of Commands
        aliases: p
        usage: |
            /<command> - List of commands
            /<command> buy [id/"universal"] - Buys permit
            /<command> cost [id] - Display cost of certain permit. No param displays price for universal permit
            /<command> time {id} - Displays remaining time for permit. No param displays all owned permits
            /<command> view {id} - Returns if a permit is required for this block. No param returns all required permits
            /<command> wall

permissions:
    MinePermit.exempt:
        description: Exempts player from mining permit requirements
        default: op
